# Generated by Django 3.2.6 on 2021-08-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
