# Generated by Django 3.2.6 on 2021-08-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment_blog_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog_views',
        ),
        migrations.AddField(
            model_name='article',
            name='blog_views',
            field=models.IntegerField(default=0),
        ),
    ]
