# Generated by Django 3.2.6 on 2021-08-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210823_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='blog_views',
            new_name='blog_view',
        ),
    ]
